export const QueryKeys = {
    PRODUCTS: "products",
    SIZES: "sizes",
    COLORS: "colors",
    SHOPNOWS:"shopnows",
    SWIPERS:"swipers",
    DISCOVERNOWS:"discovernows",
    INSTASWIPERS:"instaswipers",
    LIKES:"likes",
    RESULTS:"results",
    BLOGS:"blogs",
    DETAILSWIPERS:"detailswipers",
    CATEGORIES:"categories",
    FILTERS:"filters",
  };